#!/usr/bin/env python3
"""Pioneer DataLabs build step: single source of truth for every ledger.

Canonical data lives in:
    catalog.json                          (site root)
    netlify/functions/dl03-answers.json   (MBTA ledger)
    netlify/functions/dl01-answers.json   (State Tax Atlas ledger)
    netlify/functions/dl02-answers.json   (Florida ledger)
    netlify/functions/dl04-answers.json   (electricity ledger)

This script regenerates every embedded copy from the canonical files:
    index.html            const DATA (catalog + answers; audit preserved)
    mbta/index.html       const ANSWERS
    tax-atlas/index.html  STATES, *_META, DEFAULT_SOURCES, STATE_SOURCES, CAPTIONS
    florida-insurance/index.html  chart series, dateline, footer, keyed headlines
    electricity/index.html  chart payload, dateline, KPI band, footer
    netlify/functions/catalog.json        copy of root catalog.json

It runs locally (python3 scripts/inject_data.py) and as the Netlify build
command, so a deploy can never ship pages out of sync with the ledgers.
Edit the canonical JSON, never the generated blocks (marked DATA:BEGIN/END).
Idempotent: running twice changes nothing.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load(rel):
    with open(ROOT / rel, encoding="utf-8") as f:
        return json.load(f)


def jdump(obj):
    # Compact, ascii-safe, deterministic: stable bytes keep diffs reviewable.
    return json.dumps(obj, ensure_ascii=True, separators=(",", ":"), sort_keys=False)


def replace_block(text, name, payload, path, style="js"):
    """Regenerate a marked block. style 'js' uses /* */ markers (script
    regions); style 'html' uses <!-- --> markers (markup regions)."""
    if style == "html":
        begin = "<!-- DATA:BEGIN " + name
        end = "<!-- DATA:END " + name + " -->"
        tail = " (generated by scripts/inject_data.py; edit the canonical JSON, not this block) -->"
    else:
        begin = "/* DATA:BEGIN " + name
        end = "/* DATA:END " + name + " */"
        tail = " (generated by scripts/inject_data.py; edit the canonical JSON, not this block) */"
    pattern = re.compile(re.escape(begin) + r"[^\n]*\n.*?" + re.escape(end), re.S)
    if not pattern.search(text):
        sys.exit(f"FATAL: marker {name!r} not found in {path}")
    return pattern.sub(lambda _: begin + tail + "\n" + payload + "\n" + end, text)


MONTH_END = {
    "January": ("Jan", 31), "February": ("Feb", 28), "March": ("Mar", 31),
    "April": ("Apr", 30), "May": ("May", 31), "June": ("Jun", 30),
    "July": ("Jul", 31), "August": ("Aug", 31), "September": ("Sep", 30),
    "October": ("Oct", 31), "November": ("Nov", 30), "December": ("Dec", 31),
}
ONES = {
    1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
    7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve",
    13: "thirteen", 14: "fourteen", 15: "fifteen", 16: "sixteen",
    17: "seventeen", 18: "eighteen", 19: "nineteen", 20: "twenty",
}


def fl_data_through(as_of):
    """Turn ledger as_of ('June 2026' or '2026-06') into 'Jun 30, 2026'."""
    if as_of.split(" ")[0] in MONTH_END:
        name, year = as_of.split(" ")
        abbr, day = MONTH_END[name]
        return f"{abbr} {day}, {year}"
    parts = as_of.split("-")
    months = list(MONTH_END.keys())
    name = months[int(parts[1]) - 1]
    abbr, day = MONTH_END[name]
    return f"{abbr} {day}, {parts[0]}"


def fl_money_delta(n):
    sign = "\u2212" if n < 0 else "+"
    return f"{sign}${abs(n):,}"


def fl_county_list(rows, key="change"):
    parts = [f"{r['county']} ({fl_money_delta(r[key])})" for r in rows]
    if len(parts) <= 1:
        return parts[0] if parts else ""
    if len(parts) == 2:
        return parts[0] + " and " + parts[1]
    return ", ".join(parts[:-1]) + ", and " + parts[-1]


def inject_florida(dl02, text, path):
    """Regenerate Florida chart consts and the headlines that must track them."""
    kf = dl02["citizens_key_facts"]
    page = dl02.get("page") or {}
    sw = dl02["statewide_premiums"]
    ranks = dl02["county_rankings"]
    n_up = ranks["counties_total"] - ranks["counties_with_declines"]
    fl = {
        "as_of": dl02["as_of"],
        "data_through": fl_data_through(dl02["as_of"]),
        "revised": page.get("revised", ""),
        "version": page.get("version", "1.0"),
        "pif": kf["latest"]["policies"],
        "pif_fmt": f"{kf['latest']['policies']:,}",
        "peak": kf["peak"]["policies"],
        "peak_fmt": f"{kf['peak']['policies']:,}",
        "decline_pct": abs(kf["decline_from_peak_pct"]),
    }
    charts = "\n".join([
        "const pif=" + jdump([[e["m"], e["v"]] for e in dl02["citizens_policies_monthly"]]) + ";",
        "const qtr=" + jdump([[e["q"], e["policies"], e["premium_usd"], e["exposure_usd"]]
                              for e in dl02["citizens_quarterly"]]) + ";",
        "const cty=" + jdump([[k, c["incl_wind"], c["ex_wind"], c["incl_wind_2025_09"]]
                              for k, c in sorted(dl02["county_premiums"].items())]) + ";",
        "const FLSW=" + jdump({"labels": sw["labels"], "avg": sw["avg_premium"],
                               "c100": sw["cost_per_100k"]}) + ";",
        "const FLCR=" + jdump({"labels": [e["year"] for e in dl02["combined_ratio"]],
                               "data": [e["pct"] for e in dl02["combined_ratio"]]}) + ";",
        "const FLSTAT=" + jdump({
            "labels": [e["year"] for e in dl02["citizens_statutory_results"]],
            "uw": [e["underwriting_m"] for e in dl02["citizens_statutory_results"]],
            "ni": [e["net_income_m"] for e in dl02["citizens_statutory_results"]],
        }) + ";",
        "const FLMC=" + jdump([[e["year"], e["fl_share_us_claims_pct"], e["fl_share_us_suits_pct"]]
                               for e in dl02["litigation_share"]]) + ";",
        "const FLINFLOW=" + jdump([[e["period"], e["implied_inflow_per_100_takeouts"]]
                                   for e in dl02["takeout_net_inflow"]]) + ";",
        "const FLRT=" + jdump({
            "y": [e["year"] for e in dl02["risk_transfer"]],
            "f": [e["cat_fund_coverage_bn"] for e in dl02["risk_transfer"]],
            "p": [e["private_capital_coverage_bn"] for e in dl02["risk_transfer"]],
            "s": [e["reinsurance_premium_pct_of_dwp"] for e in dl02["risk_transfer"]],
        }) + ";",
        "const FLPML=" + jdump({
            "vintages": [[e["label"], e["source"]] for e in dl02["pml_vintages"]],
            "abs": [e["abs_bn"] for e in dl02["pml_vintages"]],
            "tiv": [e["tiv_per_100"] for e in dl02["pml_vintages"]],
            "pol": [e["per_policy_k"] for e in dl02["pml_vintages"]],
        }) + ";",
        "const FLCONC=" + jdump(dl02["concentration"]) + ";",
        "const FL=" + jdump(fl) + ";",
    ])
    text = replace_block(text, "florida-charts", charts, path)
    dateline = (
        f'    <span>Data through <b>{fl["data_through"]}</b></span>\n'
        f'    <span>Revised <b>{fl["revised"]}</b></span>\n'
        f'    <span>Version <b>{fl["version"]}</b></span>'
    )
    text = replace_block(text, "florida-dateline", dateline, path, style="html")
    text = replace_block(text, "florida-pif", fl["pif_fmt"], path, style="html")
    decl = fl_county_list(ranks["largest_declines_since_2025_09"][:4])
    inc = fl_county_list(ranks["largest_increases_since_2025_09"][:2])
    n_up_word = ONES.get(n_up, str(n_up))
    change = (
        f"The largest declines came in {decl}, consistent with the largest "
        f"approved Citizens cuts landing in South Florida; {n_up_word} counties "
        f"rose modestly, led by {inc}."
    )
    text = replace_block(text, "florida-county-change", change, path, style="html")
    revised_long = fl["revised"]
    for full, (short, _) in MONTH_END.items():
        if revised_long.startswith(short + " "):
            revised_long = full + revised_long[len(short):]
            break
    through_day = fl["data_through"].split()[1]
    through_long = dl02["as_of"].replace(" ", f" {through_day} ")
    footer = (
        f"    <div>Florida Insurance Watch &middot; Version {fl['version']} "
        f"&middot; Data through {through_long} &middot; "
        f"Revised {revised_long}</div>"
    )
    text = replace_block(text, "florida-footer-meta", footer, path, style="html")
    return text


def inject_electricity(dl04, text, path):
    """Regenerate the electricity page payload and the headlines that track it."""
    latest = dl04["latest"]
    page = dl04.get("page") or {}
    year = dl04["data_year"]
    payload = {
        "year": year,
        "as_of": dl04["as_of"],
        "revised": page.get("revised", ""),
        "version": page.get("version", "1.0"),
        "entities": dl04["entities"],
        "latest": latest,
        "states": dl04["latest_states"],
        "price_trend": dl04["price_trend"],
        "derived": {
            "highest_five": dl04["derived"]["highest_five"],
            "lowest_five": dl04["derived"]["lowest_five"],
            "us_change_from_first_pct": dl04["derived"]["us_change_from_first_pct"],
            "ma_change_from_first_pct": dl04["derived"]["ma_change_from_first_pct"],
            "us_price_first_year": dl04["derived"]["us_price_first_year"],
            "ma_price_first_year": dl04["derived"]["ma_price_first_year"],
            "massachusetts_rank": dl04["derived"]["massachusetts_rank"],
            "n_ranked": dl04["derived"]["n_ranked"],
        },
    }
    text = replace_block(text, "electricity-data", "const DL04=" + jdump(payload) + ";", path)
    dateline = (
        f'    <span>Data through <b>Dec 31, {year}</b></span>\n'
        f'    <span>Revised <b>{page.get("revised", "")}</b></span>\n'
        f'    <span>Version <b>{page.get("version", "1.0")}</b></span>'
    )
    text = replace_block(text, "electricity-dateline", dateline, path, style="html")
    us_p = f"{latest['us']['price_cents']:.2f}"
    ma_p = f"{latest['ma']['price_cents']:.2f}"
    hi_p = f"{latest['highest']['price_cents']:.2f}"
    lo_p = f"{latest['lowest']['price_cents']:.2f}"
    us_yoy = latest["us"].get("yoy_pct")
    ma_yoy = latest["ma"].get("yoy_pct")
    us_yoy_html = (
        f'<span class="{"up" if us_yoy and us_yoy > 0 else "dn"}">'
        f'{us_yoy:+.1f}% from {year - 1}</span>'
        if us_yoy is not None else f"EIA U.S. Total, {year}"
    )
    ma_yoy_txt = (
        f"{ma_yoy:+.1f} percent from {year - 1}"
        if ma_yoy is not None else f"all-sector average, {year}"
    )
    kpis = (
        f'      <div class="cell">\n'
        f'        <div class="cl">U.S. average, {year}</div>\n'
        f'        <div class="cv">{us_p}&cent;</div>\n'
        f'        <div class="cd">All-sector average retail price, EIA U.S. Total row, not an average of the state prices (SRC-401). {us_yoy_html}.</div>\n'
        f'        <div class="cd" style="margin-top:8px"><b>Why it matters:</b> This is the national price the rest of the page is measured against.</div>\n'
        f'        <div class="csrc">Source: EIA Form EIA-861 / Electric Power Annual table 2.10 (SRC-401)</div>\n'
        f'      </div>\n'
        f'      <div class="cell">\n'
        f'        <div class="cl">Massachusetts</div>\n'
        f'        <div class="cv">{ma_p}&cent;</div>\n'
        f'        <div class="cd">Rank {latest["ma"]["rank"]} of {latest["ma"]["n"]} states and D.C. (derived, SRC-401). {ma_yoy_txt}.</div>\n'
        f'        <div class="cd" style="margin-top:8px"><b>Why it matters:</b> Massachusetts sits well above the national average, with the rest of New England.</div>\n'
        f'        <div class="csrc">Source: EIA Form EIA-861 (SRC-401)</div>\n'
        f'      </div>\n'
        f'      <div class="cell">\n'
        f'        <div class="cl">Highest / lowest</div>\n'
        f'        <div class="cv">{latest["highest"]["st"]} {float(latest["highest"]["price_cents"]):.2f}</div>\n'
        f'        <div class="cd">{latest["highest"]["name"]} is the highest all-sector average; {latest["lowest"]["name"]} is the lowest at {lo_p} cents (SRC-401).</div>\n'
        f'        <div class="cd" style="margin-top:8px"><b>Why it matters:</b> The spread is the story: the same kilowatthour costs several times more in some states than in others.</div>\n'
        f'        <div class="csrc">Source: EIA Form EIA-861 (SRC-401)</div>\n'
        f'      </div>'
    )
    text = replace_block(text, "electricity-kpis", kpis, path, style="html")
    us_dir = "up" if us_yoy and us_yoy > 0 else "down"
    lead = (
        f'The United States all-sector average was <b>{us_p} cents</b> per kilowatthour '
        f'in {year}, {us_dir} {abs(us_yoy):.1f} percent from {year - 1} (SRC-401). '
        f'Massachusetts paid <b>{ma_p} cents</b>, rank {latest["ma"]["rank"]} of '
        f'{latest["ma"]["n"]} (derived, SRC-401). {latest["highest"]["name"]} was '
        f'highest at {hi_p} cents and {latest["lowest"]["name"]} lowest at {lo_p} '
        f'cents (SRC-401).'
    )
    text = replace_block(text, "electricity-lead", lead, path, style="html")
    revised_long = page.get("revised", "")
    for full, (short, _) in MONTH_END.items():
        if revised_long.startswith(short + " "):
            revised_long = full + revised_long[len(short):]
            break
    footer = (
        f"    <div>Retail Electricity Prices &middot; Version {page.get('version', '1.0')} "
        f"&middot; Data through December 31, {year} &middot; "
        f"Revised {revised_long}</div>"
    )
    text = replace_block(text, "electricity-footer-meta", footer, path, style="html")
    return text


def extract_json_after(text, prefix, path):
    """Return the parsed JSON object literal that follows `prefix` on its line."""
    m = re.search(re.escape(prefix) + r"(.*?);\s*$", text, re.M)
    if not m:
        sys.exit(f"FATAL: could not find {prefix!r} in {path}")
    return json.loads(m.group(1))


def main():
    catalog = load("catalog.json")
    dl03 = load("netlify/functions/dl03-answers.json")
    dl01 = load("netlify/functions/dl01-answers.json")
    dl02 = load("netlify/functions/dl02-answers.json")
    dl04 = load("netlify/functions/dl04-answers.json")
    changed = []

    # ---- index.html: const DATA = {catalog, answers, audit} + desk stats ----
    p = ROOT / "index.html"
    text = p.read_text(encoding="utf-8")
    data = extract_json_after(text, "const DATA = ", p)
    data["catalog"] = catalog
    data["answers"] = dl03
    # Desk-card stats derived from the atlas ledger, so front-door copy
    # cannot drift from the data (the count was once hardcoded).
    dl01d = {
        "active_or_ballot": len(dl01["derived"]["states_with_active_or_ballot_vehicle"]),
        "ballot": dl01["derived"]["states_by_proposal_status"]
                       .get("Certified for the 2026 ballot", {}).get("count", 0),
        "as_of": dl01["as_of"],
    }
    dl04d = {
        "year": dl04["data_year"],
        "us_price": dl04["latest"]["us"]["price_cents"],
        "us_price_fmt": f"{dl04['latest']['us']['price_cents']:.2f}",
        "ma_price_fmt": f"{dl04['latest']['ma']['price_cents']:.2f}",
        "us_yoy": dl04["latest"]["us"].get("yoy_pct"),
        "highest_name": dl04["latest"]["highest"]["name"],
        "highest_price_fmt": f"{dl04['latest']['highest']['price_cents']:.2f}",
        "as_of": dl04["as_of"],
        "us_trend": [[e["y"], e["v"]] for e in dl04["price_trend"]["US"]],
    }
    front_payload = (
        "const DATA = " + jdump(data) + ";\n"
        + "const DL01D = " + jdump(dl01d) + ";\n"
        + "const DL04D = " + jdump(dl04d) + ";"
    )
    new = replace_block(text, "front-data", front_payload, p)

    # ---- index.html: FL chart series projected from the DL-02 ledger ----
    fl_consts = "\n".join([
        "const FLPIF=" + jdump([[e["m"], e["v"]] for e in dl02["citizens_policies_monthly"]]) + ";",
        "const FLCTY=" + jdump([[k, c["incl_wind"], c["ex_wind"], c["incl_wind_2025_09"]]
                                for k, c in sorted(dl02["county_premiums"].items())]) + ";",
        "const FLLIT=" + jdump([[e["year"], e["fl_share_us_claims_pct"], e["fl_share_us_suits_pct"]]
                                for e in dl02["litigation_share"]]) + ";",
        "const FLRT=" + jdump([[e["year"], e["cat_fund_coverage_bn"], e["private_capital_coverage_bn"]]
                               for e in dl02["risk_transfer"]]) + ";",
        "const FLTK=" + jdump([[e["period"], e["implied_inflow_per_100_takeouts"]]
                               for e in dl02["takeout_net_inflow"]]) + ";",
    ])
    new = replace_block(new, "front-fl-data", fl_consts, p)
    fl_rev = (dl02.get("page") or {}).get("revised", "")
    revised_long = fl_rev
    for full, (short, _) in MONTH_END.items():
        if revised_long.startswith(short + " "):
            revised_long = full + revised_long[len(short):]
            break
    front_dl = (
        f"Series through {dl02['as_of']}. "
        f"Revised {revised_long}."
    )
    new = replace_block(new, "front-dateline", front_dl, p, style="html")
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("index.html")

    # ---- mbta/index.html: const ANSWERS ----
    p = ROOT / "mbta/index.html"
    text = p.read_text(encoding="utf-8")
    new = replace_block(text, "mbta-data", "const ANSWERS=" + jdump(dl03) + ";", p)
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("mbta/index.html")

    # ---- tax-atlas/index.html: data consts + captions ----
    p = ROOT / "tax-atlas/index.html"
    text = p.read_text(encoding="utf-8")
    consts = "\n".join(
        [
            "var STATES = " + jdump(dl01["states"]) + ";",
            "var STATUS_META = " + jdump(dl01["meta"]["status"]) + ";",
            "var RISK_META = " + jdump(dl01["meta"]["risk"]) + ";",
            "var BALLOT_META = " + jdump(dl01["meta"]["ballot"]) + ";",
            "var PROPOSAL_META = " + jdump(dl01["meta"]["proposal"]) + ";",
            "var DEFAULT_SOURCES = " + jdump(dl01["default_sources"]) + ";",
            "var STATE_SOURCES = " + jdump(dl01["state_sources"]) + ";",
        ]
    )
    new = replace_block(text, "tax-atlas-data", consts, p)
    new = replace_block(
        new, "tax-atlas-captions", "var CAPTIONS = " + jdump(dl01["captions"]) + ";", p
    )

    # Events watch list: phase headers and details generated from the ledger,
    # so the engine and the page read the same dated list.
    def esc(s):
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    ev_lines = []
    for ph in dl01["events"]["phases"]:
        ev_lines.append('    <div class="ev-ph">' + esc(ph["label"]) + "</div>")
        for e in ph["events"]:
            multi = " multi" if len(e["states"]) > 1 else ""
            ev_lines.append(
                '    <details class="ev"><summary><span class="d">' + esc(e["date"])
                + '</span><span class="ab2' + multi + '">' + esc("·".join(e["states"]))
                + '</span><span class="wt">' + esc(e["title"])
                + '</span></summary><p class="dtl">' + esc(e["detail"]) + "</p></details>"
            )
    new = replace_block(new, "tax-atlas-events", "\n".join(ev_lines), p, style="html")
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("tax-atlas/index.html")

    # ---- florida-insurance/index.html: charts + keyed headlines ----
    p = ROOT / "florida-insurance/index.html"
    text = p.read_text(encoding="utf-8")
    new = inject_florida(dl02, text, p)
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("florida-insurance/index.html")

    # ---- electricity/index.html: charts + keyed headlines ----
    p = ROOT / "electricity/index.html"
    text = p.read_text(encoding="utf-8")
    new = inject_electricity(dl04, text, p)
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("electricity/index.html")

    # ---- netlify/functions/catalog.json: copy of root ----
    p = ROOT / "netlify/functions/catalog.json"
    src = (ROOT / "catalog.json").read_text(encoding="utf-8")
    if not p.exists() or p.read_text(encoding="utf-8") != src:
        p.write_text(src, encoding="utf-8")
        changed.append("netlify/functions/catalog.json")

    print("inject_data:", ("updated " + ", ".join(changed)) if changed else "everything in sync")


if __name__ == "__main__":
    main()
