#!/usr/bin/env python3
"""Pioneer DataLabs build step: single source of truth for every ledger.

Canonical data lives in:
    catalog.json                          (site root)
    suite/apps.json                       (suite registry)
    netlify/functions/dl03-answers.json   (MBTA ledger)
    netlify/functions/dl01-answers.json   (State Wealth Taxes ledger)
    netlify/functions/dl02-answers.json   (Florida ledger)
    netlify/functions/dl04-answers.json   (electricity ledger)
    netlify/functions/dl05-answers.json   (pensions ledger)
    netlify/functions/dlXX-answers.json   (suite ledgers, DL-06 onward)

This script regenerates every embedded copy from the canonical files:
    index.html            const DATA (catalog + answers; leftover Tableau audit dropped)
    mbta/index.html       const ANSWERS
    tax-atlas/index.html  STATES, *_META, DEFAULT_SOURCES, STATE_SOURCES, CAPTIONS
    florida-insurance/index.html  chart series, dateline, footer, keyed headlines
    electricity/index.html  chart payload, dateline, KPI band, footer
    pensions/index.html     chart payload, dateline, KPI band, footer
    <slug>/index.html     suite pages (DL-06 onward)
    netlify/functions/catalog.json        copy of root catalog.json

It runs locally (python3 scripts/inject_data.py) and as the Netlify build
command, so a deploy can never ship pages out of sync with the ledgers.
Edit the canonical JSON, never the generated blocks (marked DATA:BEGIN/END).
Idempotent: running twice changes nothing.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from suite_common import paper_date, paper_dateline  # noqa: E402


def load(rel):
    with open(ROOT / rel, encoding="utf-8") as f:
        return json.load(f)


def jdump(obj):
    # Compact, ascii-safe, deterministic: stable bytes keep diffs reviewable.
    return json.dumps(obj, ensure_ascii=True, separators=(",", ":"), sort_keys=False)


def slim_answers(answers):
    """Page-side lens payload: question, number, context, cite. No extras."""
    out = {}
    for key, rec in (answers or {}).items():
        if not isinstance(rec, dict) or not rec.get("value"):
            continue
        out[key] = {
            "q": rec.get("q") or "",
            "value": rec.get("value") or "",
            "context": rec.get("context") or "",
            "src_id": rec.get("src_id") or "",
            "geo": rec.get("geo") or "",
            "vintage": rec.get("vintage") or "",
            "cite": rec.get("cite") or "",
            "kind": rec.get("kind") or "",
        }
    return out


def has_block(text, name, style="js"):
    begin = ("<!-- DATA:BEGIN " if style == "html" else "/* DATA:BEGIN ") + name
    return begin in text


def replace_block(text, name, payload, path, style="js"):
    """Regenerate a marked block. style 'js' uses /* */ markers (script
    regions); style 'html' uses <!-- --> markers (markup regions)."""
    if style == "html":
        begin = "<!-- DATA:BEGIN " + name
        end = "<!-- DATA:END " + name + " -->"
        tail = " (generated by scripts/inject_data.py; edit the canonical JSON, not this block) -->"
    else:
        begin = "/* DATA:BEGIN " + name
        end = "/* DATA:END " + name + " */"
        tail = " (generated by scripts/inject_data.py; edit the canonical JSON, not this block) */"
    pattern = re.compile(re.escape(begin) + r"[^\n]*\n.*?" + re.escape(end), re.S)
    if not pattern.search(text):
        sys.exit(f"FATAL: marker {name!r} not found in {path}")
    return pattern.sub(lambda _: begin + tail + "\n" + payload + "\n" + end, text)


MONTH_END = {
    "January": ("Jan", 31), "February": ("Feb", 28), "March": ("Mar", 31),
    "April": ("Apr", 30), "May": ("May", 31), "June": ("Jun", 30),
    "July": ("Jul", 31), "August": ("Aug", 31), "September": ("Sep", 30),
    "October": ("Oct", 31), "November": ("Nov", 30), "December": ("Dec", 31),
}
ONES = {
    1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
    7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve",
    13: "thirteen", 14: "fourteen", 15: "fifteen", 16: "sixteen",
    17: "seventeen", 18: "eighteen", 19: "nineteen", 20: "twenty",
}


def fl_data_through(as_of):
    """Turn ledger as_of ('June 2026' or '2026-06') into 'Jun 30, 2026'."""
    if as_of.split(" ")[0] in MONTH_END:
        name, year = as_of.split(" ")
        abbr, day = MONTH_END[name]
        return f"{abbr} {day}, {year}"
    parts = as_of.split("-")
    months = list(MONTH_END.keys())
    name = months[int(parts[1]) - 1]
    abbr, day = MONTH_END[name]
    return f"{abbr} {day}, {parts[0]}"


def fl_money_delta(n):
    sign = "\u2212" if n < 0 else "+"
    return f"{sign}${abs(n):,}"


def fl_county_list(rows, key="change"):
    parts = [f"{r['county']} ({fl_money_delta(r[key])})" for r in rows]
    if len(parts) <= 1:
        return parts[0] if parts else ""
    if len(parts) == 2:
        return parts[0] + " and " + parts[1]
    return ", ".join(parts[:-1]) + ", and " + parts[-1]


def inject_florida(dl02, text, path):
    """Regenerate Florida chart consts and the headlines that must track them."""
    kf = dl02["citizens_key_facts"]
    page = dl02.get("page") or {}
    sw = dl02["statewide_premiums"]
    ranks = dl02["county_rankings"]
    n_up = ranks["counties_total"] - ranks["counties_with_declines"]
    fl = {
        "as_of": dl02["as_of"],
        "data_through": fl_data_through(dl02["as_of"]),
        "revised": page.get("revised", ""),
        "version": page.get("version", "1.0"),
        "pif": kf["latest"]["policies"],
        "pif_fmt": f"{kf['latest']['policies']:,}",
        "peak": kf["peak"]["policies"],
        "peak_fmt": f"{kf['peak']['policies']:,}",
        "decline_pct": abs(kf["decline_from_peak_pct"]),
    }
    charts = "\n".join([
        "const pif=" + jdump([[e["m"], e["v"]] for e in dl02["citizens_policies_monthly"]]) + ";",
        "const qtr=" + jdump([[e["q"], e["policies"], e["premium_usd"], e["exposure_usd"]]
                              for e in dl02["citizens_quarterly"]]) + ";",
        "const cty=" + jdump([[k, c["incl_wind"], c["ex_wind"], c["incl_wind_2025_09"]]
                              for k, c in sorted(dl02["county_premiums"].items())]) + ";",
        "const FLSW=" + jdump({"labels": sw["labels"], "avg": sw["avg_premium"],
                               "c100": sw["cost_per_100k"]}) + ";",
        "const FLCR=" + jdump({"labels": [e["year"] for e in dl02["combined_ratio"]],
                               "data": [e["pct"] for e in dl02["combined_ratio"]]}) + ";",
        "const FLSTAT=" + jdump({
            "labels": [e["year"] for e in dl02["citizens_statutory_results"]],
            "uw": [e["underwriting_m"] for e in dl02["citizens_statutory_results"]],
            "ni": [e["net_income_m"] for e in dl02["citizens_statutory_results"]],
        }) + ";",
        "const FLMC=" + jdump([[e["year"], e["fl_share_us_claims_pct"], e["fl_share_us_suits_pct"]]
                               for e in dl02["litigation_share"]]) + ";",
        "const FLINFLOW=" + jdump([[e["period"], e["implied_inflow_per_100_takeouts"]]
                                   for e in dl02["takeout_net_inflow"]]) + ";",
        "const FLRT=" + jdump({
            "y": [e["year"] for e in dl02["risk_transfer"]],
            "f": [e["cat_fund_coverage_bn"] for e in dl02["risk_transfer"]],
            "p": [e["private_capital_coverage_bn"] for e in dl02["risk_transfer"]],
            "s": [e["reinsurance_premium_pct_of_dwp"] for e in dl02["risk_transfer"]],
        }) + ";",
        "const FLPML=" + jdump({
            "vintages": [[e["label"], e["source"]] for e in dl02["pml_vintages"]],
            "abs": [e["abs_bn"] for e in dl02["pml_vintages"]],
            "tiv": [e["tiv_per_100"] for e in dl02["pml_vintages"]],
            "pol": [e["per_policy_k"] for e in dl02["pml_vintages"]],
        }) + ";",
        "const FLCONC=" + jdump(dl02["concentration"]) + ";",
        "const FL=" + jdump(fl) + ";",
    ])
    text = replace_block(text, "florida-charts", charts, path)
    dateline = paper_dateline(f"Data through {fl['data_through']}", fl["revised"])
    text = replace_block(text, "florida-dateline", dateline, path, style="html")
    text = replace_block(text, "florida-pif", fl["pif_fmt"], path, style="html")
    md = dl02["county_premiums"]["Miami-Dade"]
    text = replace_block(
        text,
        "florida-miami-premium",
        f"${md['incl_wind']:,}",
        path,
        style="html",
    )
    text = replace_block(
        text,
        "florida-miami-change",
        fl_money_delta(md["incl_wind"] - md["incl_wind_2025_09"]),
        path,
        style="html",
    )
    decl = fl_county_list(ranks["largest_declines_since_2025_09"][:4])
    inc = fl_county_list(ranks["largest_increases_since_2025_09"][:2])
    n_up_word = ONES.get(n_up, str(n_up))
    change = (
        f"The largest declines came in {decl}, consistent with the largest "
        f"approved Citizens cuts landing in South Florida; {n_up_word} counties "
        f"rose modestly, led by {inc}."
    )
    text = replace_block(text, "florida-county-change", change, path, style="html")
    revised_long = fl["revised"]
    for full, (short, _) in MONTH_END.items():
        if revised_long.startswith(short + " "):
            revised_long = full + revised_long[len(short):]
            break
    through_day = fl["data_through"].split()[1]
    through_long = dl02["as_of"].replace(" ", f" {through_day} ")
    footer = (
        f"    <div>Florida Homeowners Insurance "
        f"&middot; Data through {through_long} &middot; "
        f"Revised {revised_long}</div>"
    )
    text = replace_block(text, "florida-footer-meta", footer, path, style="html")
    return text


def inject_electricity(dl04, text, path):
    """Regenerate the electricity page payload and the headlines that track it."""
    latest = dl04["latest"]
    page = dl04.get("page") or {}
    year = dl04["data_year"]
    sys.path.insert(0, str(ROOT / "scripts"))
    from audience_starters import starters_html  # noqa: E402
    from page_voice import flagship_voice, takeaways_html, answer_inner_html  # noqa: E402
    from render_suite_pages import kpi_html  # noqa: E402
    voice = flagship_voice("DL-04", dl04)
    payload = {
        "year": year,
        "as_of": dl04["as_of"],
        "revised": page.get("revised", ""),
        "version": page.get("version", "1.0"),
        "entities": dl04["entities"],
        "latest": latest,
        "states": dl04["latest_states"],
        "price_trend": dl04["price_trend"],
        "residential": (dl04.get("latest") or {}).get("residential"),
        "residential_states": dl04.get("residential_states") or [],
        "residential_trend": dl04.get("residential_trend") or {},
        "derived": {
            "highest_five": dl04["derived"]["highest_five"],
            "lowest_five": dl04["derived"]["lowest_five"],
            "us_change_from_first_pct": dl04["derived"]["us_change_from_first_pct"],
            "ma_change_from_first_pct": dl04["derived"]["ma_change_from_first_pct"],
            "us_price_first_year": dl04["derived"]["us_price_first_year"],
            "ma_price_first_year": dl04["derived"]["ma_price_first_year"],
            "massachusetts_rank": dl04["derived"]["massachusetts_rank"],
            "n_ranked": dl04["derived"]["n_ranked"],
        },
        "answers": slim_answers((voice or {}).get("answers")),
    }
    text = replace_block(text, "electricity-data", "const DL04=" + jdump(payload) + ";", path)
    dateline = paper_dateline(f"Calendar year {year}", page.get("revised", ""))
    text = replace_block(text, "electricity-dateline", dateline, path, style="html")
    if has_block(text, "electricity-takeaways", style="html") and voice.get("takeaways"):
        text = replace_block(text, "electricity-takeaways", takeaways_html(voice["takeaways"]), path, style="html")
    if has_block(text, "electricity-answer", style="html") and voice.get("answer"):
        text = replace_block(
            text,
            "electricity-answer",
            answer_inner_html(voice["answer"], voice.get("answers")),
            path,
            style="html",
        )
    kpis = kpi_html(voice.get("kpis") or [])
    text = replace_block(text, "electricity-kpis", kpis, path, style="html")
    text = replace_block(text, "electricity-lead", voice.get("lead") or "", path, style="html")
    if has_block(text, "electricity-cite", style="html") and voice.get("cite"):
        text = replace_block(text, "electricity-cite", voice["cite"], path, style="html")
    revised_long = page.get("revised", "")
    for full, (short, _) in MONTH_END.items():
        if revised_long.startswith(short + " "):
            revised_long = full + revised_long[len(short):]
            break
    footer = (
        f"    <div>Retail Electricity Prices "
        f"&middot; Data through December 31, {year} &middot; "
        f"Revised {revised_long}</div>"
    )
    text = replace_block(text, "electricity-footer-meta", footer, path, style="html")
    return text


def usd_prose(n):
    """House style: $ on the figure, million/billion spelled out."""
    sign = "-" if n < 0 else ""
    a = abs(n)
    if a >= 1e9:
        v = a / 1e9
        fmt = f"{v:.1f}" if abs(v - round(v, 1)) < 0.005 else f"{v:.2f}"
        return f"{sign}${fmt} billion"
    if a >= 1e6:
        return f"{sign}${a / 1e6:.1f} million"
    return f"{sign}${a:,.0f}"


def inject_pensions(dl05, text, path):
    """Regenerate the pensions page payload and the headlines that track it."""
    page = dl05.get("page") or {}
    latest = dl05["latest"]
    derived = dl05["derived"]
    boards = [
        {
            "id": b["id"],
            "name": b["name"],
            "valuation_year": b["valuation_year"],
            "funded_pct": b["funded_pct"],
            "ual": b["ual"],
            "aal": b["aal"],
            "active": b["active"],
            "retired": b["retired"],
            "return_1y_pct": b.get("return_1y_pct"),
            "return_5y_pct": b.get("return_5y_pct"),
            "return_10y_pct": b.get("return_10y_pct"),
            "rank": b["rank"],
            "n": b["n"],
        }
        for b in dl05["boards"]
    ]
    payload = {
        "as_of": dl05["as_of"],
        "board_valuation_through": dl05["board_valuation_through"],
        "returns_year": dl05["returns_year"],
        "retiree_year": dl05["retiree_year"],
        "search_year": dl05.get("search_year") or dl05["retirees"].get("search_year"),
        "revised": page.get("revised", ""),
        "version": page.get("version", "1.0"),
        "entities": dl05["entities"],
        "latest": latest,
        "derived": {
            "n_boards": derived["n_boards"],
            "n_at_or_above_100": derived["n_at_or_above_100"],
            "n_below_60": derived["n_below_60"],
            "highest_five": derived["highest_five"],
            "lowest_five": derived["lowest_five"],
            "state_funded_pct": derived["state_funded_pct"],
            "mtrs_funded_pct": derived["mtrs_funded_pct"],
            "weighted_funded_pct": derived["weighted_funded_pct"],
            "state_rank": derived["state_rank"],
            "mtrs_rank": derived["mtrs_rank"],
            "retiree_count": derived["retiree_count"],
            "retiree_annual_amount": derived["retiree_annual_amount"],
            "retiree_avg_amount": derived["retiree_avg_amount"],
            "largest_pension": derived["largest_pension"],
        },
        "boards": boards,
        "funded_history": dl05["funded_history"],
        "retirees": {
            "yearly": dl05["retirees"]["yearly"],
            "latest": dl05["retirees"]["latest"],
            "search": dl05["retirees"].get("search"),
            "top_pensions": dl05["retirees"]["top_pensions"],
            "departments": dl05["retirees"]["departments"],
            "manifest": dl05["retirees"].get("manifest"),
        },
    }
    text = replace_block(text, "pensions-data", "const DL05=" + jdump(payload) + ";", path)
    search_year = dl05.get("search_year") or dl05["retirees"].get("search_year")
    search = (dl05["retirees"] or {}).get("search") or {}
    dateline = (
        f"Board valuations through 1 January {dl05['board_valuation_through']}"
        f" · Retiree payroll through {dl05['retiree_year']}"
        f" · Name search through {search_year}"
        + (f" · Revised {paper_date(page.get('revised', ''))}" if page.get("revised") else "")
    )
    text = replace_block(text, "pensions-dateline", dateline, path, style="html")
    st = latest["state"]
    mt = latest["mtrs"]
    ret = latest["retirees"]
    n = derived["n_boards"]
    sys.path.insert(0, str(ROOT / "scripts"))
    from page_voice import flagship_voice, takeaways_html, answer_inner_html  # noqa: E402
    from render_suite_pages import kpi_html  # noqa: E402
    voice = flagship_voice("DL-05", dl05)
    if has_block(text, "pensions-takeaways", style="html") and voice.get("takeaways"):
        text = replace_block(text, "pensions-takeaways", takeaways_html(voice["takeaways"]), path, style="html")
    if has_block(text, "pensions-answer", style="html") and voice.get("answer"):
        text = replace_block(text, "pensions-answer", answer_inner_html(voice["answer"]), path, style="html")
    text = replace_block(text, "pensions-kpis", kpi_html(voice.get("kpis") or []), path, style="html")
    text = replace_block(text, "pensions-lead", voice.get("lead") or "", path, style="html")
    if has_block(text, "pensions-cite", style="html") and voice.get("cite"):
        text = replace_block(text, "pensions-cite", voice["cite"], path, style="html")
    revised_long = page.get("revised", "")
    for full, (short, _) in MONTH_END.items():
        if revised_long.startswith(short + " "):
            revised_long = full + revised_long[len(short):]
            break
    footer = (
        f"    <div>Massachusetts Public Pensions "
        f"&middot; Board valuations through January 1, {dl05['board_valuation_through']} "
        f"&middot; Retiree payroll through {dl05['retiree_year']} "
        f"&middot; Name search through {search_year} &middot; "
        f"Revised {revised_long}</div>"
    )
    text = replace_block(text, "pensions-footer-meta", footer, path, style="html")
    lat = dl05["retirees"]["latest"]
    fig4 = (
        f'In {lat["year"]} the file has {lat["msers"]["count"]:,} MSERS retirees paid '
        f'{usd_prose(lat["msers"]["annual_amount"])} and {lat["mtrs"]["count"]:,} MTRS '
        f'retirees paid {usd_prose(lat["mtrs"]["annual_amount"])} (SRC-503). Combined '
        f'annual pensions rose {derived["retiree_amount_change_from_2011_pct"]} percent '
        f'from 2011. Name search uses the {search_year} CTHRU file'
        + (" (year-to-date)" if search and not search.get("complete") else "")
        + f', {search.get("count", 0):,} named retirees (SRC-503).'
    )
    text = replace_block(text, "pensions-fig4-note", fig4, path, style="html")
    search_lede = (
        f'Type a last name to search {search.get("count", 0):,} MSERS and MTRS '
        f'retirees in the {search_year} CTHRU file'
        + (" (year-to-date, through June)" if search_year == 2026 else "")
        + ". Names and amounts are public record. Local-board retirees are not in this file."
    )
    text = replace_block(text, "pensions-search-lede", search_lede, path, style="html")
    top_head = f'The largest State and Teacher pensions, {search_year}'
    text = replace_block(text, "pensions-top-head", top_head, path, style="html")
    return text


def extract_json_after(text, prefix, path):
    """Return the parsed JSON object literal that follows `prefix` on its line."""
    m = re.search(re.escape(prefix) + r"(.*?);\s*$", text, re.M)
    if not m:
        sys.exit(f"FATAL: could not find {prefix!r} in {path}")
    return json.loads(m.group(1))


def main():
    catalog = load("catalog.json")
    sys.path.insert(0, str(ROOT / "scripts"))
    from page_voice import apply_catalog_ma, apply_catalog_q, apply_catalog_g  # noqa: E402
    from suite_common import apply_catalog_dashboards  # noqa: E402
    apply_catalog_q(catalog)
    apply_catalog_ma(catalog)
    apply_catalog_g(catalog)
    apply_catalog_dashboards(catalog)
    (ROOT / "catalog.json").write_text(
        json.dumps(catalog, ensure_ascii=True, indent=1) + "\n", encoding="utf-8"
    )
    dl03 = load("netlify/functions/dl03-answers.json")
    dl01 = load("netlify/functions/dl01-answers.json")
    dl02 = load("netlify/functions/dl02-answers.json")
    dl04 = load("netlify/functions/dl04-answers.json")
    dl05 = load("netlify/functions/dl05-answers.json")
    changed = []

    # ---- index.html: const DATA = {catalog, answers, audit} + desk stats ----
    p = ROOT / "index.html"
    text = p.read_text(encoding="utf-8")
    data = extract_json_after(text, "const DATA = ", p)
    data["catalog"] = catalog
    data["answers"] = dl03
    data.pop("audit", None)
    # Desk-card stats derived from the atlas ledger, so front-door copy
    # cannot drift from the data (the count was once hardcoded).
    dl01d = {
        "active_or_ballot": len(dl01["derived"]["states_with_active_or_ballot_vehicle"]),
        "ballot": dl01["derived"]["states_by_proposal_status"]
                       .get("Certified for the 2026 ballot", {}).get("count", 0),
        "as_of": dl01["as_of"],
    }
    dl05d = {
        "state_funded_pct": dl05["latest"]["state"]["funded_pct"],
        "mtrs_funded_pct": dl05["latest"]["mtrs"]["funded_pct"],
        "weighted_funded_pct": dl05["derived"]["weighted_funded_pct"],
        "retiree_year": dl05["retiree_year"],
        "search_year": dl05.get("search_year") or dl05["retirees"].get("search_year"),
        "retiree_amount": dl05["latest"]["retirees"]["annual_amount"],
        "retiree_amount_fmt": usd_prose(dl05["latest"]["retirees"]["annual_amount"]),
        "retiree_count": dl05["latest"]["retirees"]["count"],
        "n_boards": dl05["latest"]["n_boards"],
        "as_of": dl05["as_of"],
        "state_trend": [
            [e["y"], e["v"]] for e in dl05["funded_history"]["state"]
        ],
    }
    front_payload = (
        "const DATA = " + jdump(data) + ";\n"
        + "const DL01D = " + jdump(dl01d) + ";\n"
        + "const DL05D = " + jdump(dl05d) + ";"
    )
    new = replace_block(text, "front-data", front_payload, p)

    # ---- index.html: FL chart series projected from the DL-02 ledger ----
    fl_consts = "\n".join([
        "const FLPIF=" + jdump([[e["m"], e["v"]] for e in dl02["citizens_policies_monthly"]]) + ";",
        "const FLCTY=" + jdump([[k, c["incl_wind"], c["ex_wind"], c["incl_wind_2025_09"]]
                                for k, c in sorted(dl02["county_premiums"].items())]) + ";",
        "const FLLIT=" + jdump([[e["year"], e["fl_share_us_claims_pct"], e["fl_share_us_suits_pct"]]
                                for e in dl02["litigation_share"]]) + ";",
        "const FLRT=" + jdump([[e["year"], e["cat_fund_coverage_bn"], e["private_capital_coverage_bn"]]
                               for e in dl02["risk_transfer"]]) + ";",
        "const FLTK=" + jdump([[e["period"], e["implied_inflow_per_100_takeouts"]]
                               for e in dl02["takeout_net_inflow"]]) + ";",
    ])
    new = replace_block(new, "front-fl-data", fl_consts, p)
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("index.html")

    # ---- mbta/index.html: const ANSWERS ----
    p = ROOT / "mbta/index.html"
    text = p.read_text(encoding="utf-8")
    new = replace_block(text, "mbta-data", "const ANSWERS=" + jdump(dl03) + ";", p)
    from page_voice import flagship_voice, answer_inner_html  # noqa: E402
    mbta_voice = flagship_voice("DL-03", dl03)
    if has_block(new, "mbta-answer", style="html") and mbta_voice.get("answer"):
        new = replace_block(new, "mbta-answer", answer_inner_html(mbta_voice["answer"]), p, style="html")
    if has_block(new, "mbta-lead", style="html") and mbta_voice.get("lead"):
        new = replace_block(new, "mbta-lead", mbta_voice["lead"], p, style="html")
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("mbta/index.html")

    # ---- tax-atlas/index.html: data consts + captions ----
    p = ROOT / "tax-atlas/index.html"
    text = p.read_text(encoding="utf-8")
    consts = "\n".join(
        [
            "var STATES = " + jdump(dl01["states"]) + ";",
            "var STATUS_META = " + jdump(dl01["meta"]["status"]) + ";",
            "var RISK_META = " + jdump(dl01["meta"]["risk"]) + ";",
            "var BALLOT_META = " + jdump(dl01["meta"]["ballot"]) + ";",
            "var PROPOSAL_META = " + jdump(dl01["meta"]["proposal"]) + ";",
            "var DEFAULT_SOURCES = " + jdump(dl01["default_sources"]) + ";",
            "var STATE_SOURCES = " + jdump(dl01["state_sources"]) + ";",
        ]
    )
    new = replace_block(text, "tax-atlas-data", consts, p)
    new = replace_block(
        new, "tax-atlas-captions", "var CAPTIONS = " + jdump(dl01["captions"]) + ";", p
    )

    # Events watch list: phase headers and details generated from the ledger,
    # so the engine and the page read the same dated list.
    def esc(s):
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    ev_lines = []
    for ph in dl01["events"]["phases"]:
        ev_lines.append('    <div class="ev-ph">' + esc(ph["label"]) + "</div>")
        for e in ph["events"]:
            multi = " multi" if len(e["states"]) > 1 else ""
            ev_lines.append(
                '    <details class="ev"><summary><span class="d">' + esc(e["date"])
                + '</span><span class="ab2' + multi + '">' + esc("·".join(e["states"]))
                + '</span><span class="wt">' + esc(e["title"])
                + '</span></summary><p class="dtl">' + esc(e["detail"]) + "</p></details>"
            )
    new = replace_block(new, "tax-atlas-events", "\n".join(ev_lines), p, style="html")
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("tax-atlas/index.html")

    # ---- florida-insurance/index.html: charts + keyed headlines ----
    p = ROOT / "florida-insurance/index.html"
    text = p.read_text(encoding="utf-8")
    new = inject_florida(dl02, text, p)
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("florida-insurance/index.html")

    # ---- electricity/index.html: charts + keyed headlines ----
    p = ROOT / "electricity/index.html"
    text = p.read_text(encoding="utf-8")
    new = inject_electricity(dl04, text, p)
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("electricity/index.html")

    # ---- pensions/index.html: charts + keyed headlines ----
    p = ROOT / "pensions/index.html"
    text = p.read_text(encoding="utf-8")
    new = inject_pensions(dl05, text, p)
    if new != text:
        p.write_text(new, encoding="utf-8")
        changed.append("pensions/index.html")

    # ---- suite pages (DL-06 onward): dateline, KPIs, chart payload ----
    sys.path.insert(0, str(ROOT / "scripts"))
    from render_suite_pages import kpi_html  # noqa: E402
    from page_voice import (  # noqa: E402
        display_as_of,
        display_lead,
        display_rows,
        takeaways_html,
        voice_for,
    )
    from suite_common import load_apps, ledger_path  # noqa: E402

    for app in load_apps():
        slug = app["slug"]
        p = ROOT / slug / "index.html"
        if not p.exists():
            continue
        led = json.loads(ledger_path(app["id"]).read_text(encoding="utf-8"))
        text = p.read_text(encoding="utf-8")
        new = text
        as_of_label = display_as_of(app["id"], led)
        revised = (led.get("page") or {}).get("revised", "")
        voice = voice_for(app, led)
        if has_block(new, slug + "-dateline", style="html"):
            new = replace_block(
                new,
                slug + "-dateline",
                paper_dateline(as_of_label, revised),
                p,
                style="html",
            )
        if has_block(new, slug + "-footer-meta", style="html"):
            new = replace_block(
                new,
                slug + "-footer-meta",
                f"    <div>{led['title']} "
                f"&middot; Data through {as_of_label} &middot; Revised {revised}</div>",
                p,
                style="html",
            )
        if has_block(new, slug + "-takeaways", style="html") and voice and voice.get("takeaways"):
            new = replace_block(new, slug + "-takeaways", takeaways_html(voice["takeaways"]), p, style="html")
        lead_txt = display_lead(voice, led)
        if has_block(new, slug + "-lead", style="html") and lead_txt:
            new = replace_block(
                new,
                slug + "-lead",
                lead_txt,
                p,
                style="html",
            )
        kpis_in = (voice or {}).get("kpis") or led.get("kpis") or []
        if has_block(new, slug + "-kpis", style="html") and kpis_in:
            new = replace_block(new, slug + "-kpis", kpi_html(kpis_in), p, style="html")
        if has_block(new, slug + "-cite", style="html") and voice and voice.get("cite"):
            new = replace_block(new, slug + "-cite", voice["cite"], p, style="html")
        if has_block(new, slug + "-data"):
            payload = {
                "tool_id": led["tool_id"],
                "as_of": led.get("as_of"),
                "rows": display_rows(led.get("rows") or []),
                "trend": led.get("trend") or {},
                "latest": led.get("latest"),
                "derived": led.get("derived") or {},
                "metric": led.get("metric"),
                "unit": led.get("unit"),
                "answers": slim_answers((voice or {}).get("answers")),
            }
            new = replace_block(new, slug + "-data", "const DL=" + jdump(payload) + ";", p)
        if new != text:
            p.write_text(new, encoding="utf-8")
            changed.append(str(p.relative_to(ROOT)))

    # ---- netlify/functions/catalog.json: copy of root ----
    p = ROOT / "netlify/functions/catalog.json"
    src = (ROOT / "catalog.json").read_text(encoding="utf-8")
    if not p.exists() or p.read_text(encoding="utf-8") != src:
        p.write_text(src, encoding="utf-8")
        changed.append("netlify/functions/catalog.json")

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from render_ops import main as render_ops
    before = {
        (ROOT / "status" / "index.html").read_text(encoding="utf-8")
        if (ROOT / "status" / "index.html").exists() else "",
        (ROOT / "changelog" / "index.html").read_text(encoding="utf-8")
        if (ROOT / "changelog" / "index.html").exists() else "",
        (ROOT / "sitemap.xml").read_text(encoding="utf-8")
        if (ROOT / "sitemap.xml").exists() else "",
    }
    render_ops()
    after = {
        (ROOT / "status" / "index.html").read_text(encoding="utf-8"),
        (ROOT / "changelog" / "index.html").read_text(encoding="utf-8"),
        (ROOT / "sitemap.xml").read_text(encoding="utf-8"),
    }
    if before != after:
        changed.append("status/index.html, changelog/index.html, sitemap.xml")

    print("inject_data:", ("updated " + ", ".join(changed)) if changed else "everything in sync")


if __name__ == "__main__":
    main()
